setTakerLimit = '1%'
setSellAmount = '100%'
setBuyAmount = '98%'

[MACD]
optInFastPeriod = 12
optInSlowPeriod = 26
optInSignalPeriod = 9

[EMAshort]
optInTimePeriod = 9

[EMAlong]
optInTimePeriod = 21

[STOCH]
optInFastKPeriod = 12
optInSlowKPeriod = 3
optInSlowDPeriod = 3

[RSI]
optInTimePeriod = 14

[thresholds]
RSIhigh = 66
RSIlow = 44
MACDhigh = 0
MACDlow = 0.88
persistance = 1
